// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var ie;

  ie = require('iced-error');

  exports.E = ie.make_errors({
    GPG: "Command line error",
    PGP_ID_COLLISION: "PGP ID collision error",
    NOT_FOUND: "Key wasn't found"
  });

}).call(this);
